language: python

python:
  - "3.7"
  - "3.8"

script:
  - python -m pytest $TRAVIS_BUILD_DIR/tests

addons:
  apt:
    packages:
      - oracle-java8-set-default

before_install:
  - python setup.py install
