language: python

python:
  - "3.8"

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.ccm/repository
    - $HOME/.ccm/scylla-repository

before_cache:
    - rm -f $HOME/.cache/pip/log/debug.log

script:
  - travis_wait 30 python -m pytest $TRAVIS_BUILD_DIR/tests

addons:
  apt:
    packages:
      - openjdk-8-jdk
      - rpm2cpio

before_install:
  - python setup.py install
  - ./ccm create temp -n 1 --scylla --version unstable/master:2020-10-25T21%3A55%3A10Z > /dev/null
  - ./ccm remove
  - ./ccm create temp-cas -n 1 --version 3.11.4 > /dev/null
  - ./ccm remove
  - docker pull scylladb/scylla-nightly:666.development-0.20201015.8068272b466
